version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      nest-mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:rootTopsecret@nest-mysql:3306/library

  nest-mysql:
    image: mysql:8
    container_name: nest-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=rootTopsecret
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p rootTopsecret' ]
      timeout: 20s
      retries: 10
    volumes:
      - nest-mysql:/var/lib/mysql

volumes:
  nest-mysql:
    name: nest-mysql-db
